export enum JsonapiActionTypes {
  REQUEST_ENTITY = '@jsonapi:REQUEST_ENTITY',
  RECEIVED_ENTITY = '@jsonapi:RECEIVED_ENTITY',
  INVALIDATE_ENTITY = '@jsonapi:INVALIDATE_ENTITY',

  REQUEST_COLLECTION = '@jsonapi:REQUEST_COLLECTION',
  RECEIVED_COLLECTION = '@jsonapi:RECEIVED_COLLECTION',
  INVALIDATE_COLLECTION = '@jsonapi:INVALIDATE_COLLECTION',

  REQUEST_NEXT_COLLECTION = '@jsonapi:REQUEST_NEXT_COLLECTION',
  RECEIVED_NEXT_COLLECTION = '@jsonapi:RECEIVED_NEXT_COLLECTION',

  // REQUEST_PREV_COLLECTION = '@jsonapi:REQUEST_PREV_COLLECTION',
  // RECEIVED_PREV_COLLECTION = '@jsonapi:RECEIVED_PREV_COLLECTION',
}
